### ISSUE TITLE
Logo missing a letter?

### ISSUE THREAD

**Issue by impressivewebs** [madebymodo/responsivizr#1]
Maybe you meant it this way, but the logo for "Responsivizr", [on the website](http://responsivizr.com/), seems to be missing the last letter "i". It says "RESPONSIVZR" (only one "i") but the domain and page's content says "Responsivizr" (one "i" on either side of the "v").

Again, maybe you meant to stylize it that way, but it appears like a mistake at first glance.

**Comment by lucasalvini** [comment]
Good catch, it's a typo!

Thank you.
